### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by mikeshultz** [ethereum/viper#269]
======================================================================
    ERROR: tests.test_parser (unittest.loader._FailedTest)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: tests.test_parser
    Traceback (most recent call last):
      File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
        module = self._get_module_from_name(name)
      File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
        __import__(name)
      File "/home/mike/dev/viper/tests/test_parser.py", line 3, in <module>
        from ethereum.tools import tester2 as t
    ModuleNotFoundError: No module named 'ethereum.tools'

**Comment by karlfloersch** [comment]
I believe you need to replace your Pyethereum installation with the most recent `state_revamp` branch: https://github.com/ethereum/pyethereum/tree/state_revamp

**Comment by mikeshultz** [comment]
That worked, thanks.

**Comment by fubuloubu** [comment]
Currently, manually installing the state_revamp branch fails for me with the current tests in [3aae8ea](https://github.com/ethereum/viper/commit/3aae8eadf3c9da6c0c3065506de967ab664a3f38):

```
ImportError: Failed to import test module: tests.test_parser
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/bryant/Documents/viper/tests/test_parser.py", line 3, in <module>
    from ethereum.tools import tester2 as t
ImportError: cannot import name 'tester2'
```
Although, it used to fail on the tools submodule so.... improvement?

```ImportError: Failed to import test module: tests.test_parser
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/bryant/Documents/viper/tests/test_parser.py", line 3, in <module>
    from ethereum.tools import tester2 as t
ModuleNotFoundError: No module named 'ethereum.tools'

**Comment by orig74** [comment]
I changed the line:

      from ethereum.tools import tester2 as t

to:

      from ethereum.tools import tester as t
and it worked for me.
Also make sure you are cloning the right branch of pyethereum e.g.:

      git clone -b state_revamp https://github.com/ethereum/pyethereum.git

**Comment by fubuloubu** [comment]
@mikeshultz this should now all be settled and work.

Close this issue?
