### ISSUE TITLE
ModuleNotFoundError: No module named 'viper.signatures'

### ISSUE THREAD

**Issue by msoedov** [ethereum/viper#367]
* viper Version: 0.0.1
* pyethereum Version: x.x.x
* OS: osx
* Python Version (python --version): Python 3.6.2
* Environment (output of `pip freeze`):
```
bitcoin==1.1.42
bumpversion==0.5.3
coverage==4.4.1
ethereum==2.0.4
pbkdf2==1.3
py==1.4.34
pycryptodome==3.4.7
pyethash==0.1.27
pysha3==1.0.2
pytest==3.2.2
pytest-cov==2.5.1
pytest-runner==2.12.1
PyYAML==3.12
repoze.lru==0.7
rlp==0.6.0
scrypt==0.8.0
viper==0.0.1
```

### What's your issue about?

```shell
(workd) ➜  workd git:(master) viper
Traceback (most recent call last):
  File "/Users/msoedov/pyenvs/workd/bin/viper", line 6, in <module>
    from viper import compiler, optimizer
  File "/Users/msoedov/pyenvs/workd/lib/python3.6/site-packages/viper/compiler.py", line 1, in <module>
    from . import parser
  File "/Users/msoedov/pyenvs/workd/lib/python3.6/site-packages/viper/parser.py", line 15, in <module>
    from .signatures.event_signature import (
ModuleNotFoundError: No module named 'viper.signatures'

```

### How can it be fixed?

Add __init__ to signature package

#### Cute Animal Picture

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsfHDlN4x6eZWa8VnGlKEwFrqT4Nc5bX2P5Yo81tK7BcixsBSUxg)

**Comment by DavidKnott** [comment]
@msoedov This issue has been fixed, if you have any more problems please create another issue.
