### ISSUE TITLE
Parser can't do multiple calls to same event with indexed params

### ISSUE THREAD

**Issue by pdaian** [ethereum/viper#373]
* viper Version: master
* pyethereum Version: 2.0.4
* OS: linux
* Python Version (python --version): 3.6

### What's your issue about?

Multiple calls to the same event with indexed parameters makes the parser throw up.

The following minimal contract triggers the issue:

```
F: __log__({_from: indexed(num)})

def a():
    log.F(0)

def b():
    log.F(0)
```

`viper test.vy` yields:

```
Traceback (most recent call last):
  File "/usr/local/bin/viper", line 4, in <module>
    __import__('pkg_resources').run_script('viper==0.0.2', 'viper')
  File "/home/phil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/phil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/EGG-INFO/scripts/viper", line 23, in <module>
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/compiler.py", line 11, in compile
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 346, in parse_tree_to_lll
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 436, in parse_func
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 436, in <listcomp>
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 447, in parse_body
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 957, in parse_stmt
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 1013, in parse_stmt
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 1148, in pack_logging_topics
IndexError: pop from empty list
```

Similarly for my ERC20 code in #366, which on compilation yields:
```
$ sha256sum ERC20.v.py 
9d27b91fd6bb16f6036cca237e6531d9df18082a7088ef6b60ecf40308b211aa  ERC20.v.py

$ viper ERC20.v.py 
Traceback (most recent call last):
  File "/usr/local/bin/viper", line 4, in <module>
    __import__('pkg_resources').run_script('viper==0.0.2', 'viper')
  File "/home/phil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/phil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/EGG-INFO/scripts/viper", line 23, in <module>
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/compiler.py", line 11, in compile
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 346, in parse_tree_to_lll
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 436, in parse_func
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 436, in <listcomp>
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 447, in parse_body
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 957, in parse_stmt
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 1013, in parse_stmt
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser.py", line 1156, in pack_logging_topics
  File "/usr/local/lib/python3.6/dist-packages/viper-0.0.2-py3.6.egg/viper/parser_utils.py", line 416, in base_type_conversion
viper.exceptions.TypeMismatchException: Typecasting from base type address to num256 unavailable
```

### How can it be fixed?

Haven't looked, filing this for reference.  Will debug myself if nobody has gotten to it in a week or so.

#### Cute Animal Picture

```
             .=     ,        =.
     _  _   /'/    )\,/,/(_   \ \
      `//-.|  (  ,\\)\//\)\/_  ) |
      //___\   `\\\/\\/\/\\///'  /
   ,-"~`-._ `"--'_   `"""`  _ \`'"~-,_
   \       `-.  '_`.      .'_` \ ,-"~`/
    `.__.-'`/   (-\        /-) |-.__,'
      ||   |     \O)  /^\ (O/  |
      `\\  |         /   `\    /
        \\  \       /      `\ /
         `\\ `-.  /' .---.--.\
           `\\/`~(, '()      ('
            /(O) \\   _,.-.,_)
           //  \\ `\'`      /
     jgs  / |  ||   `""""~"`
        /'  |__||
              `o 
```

**Comment by DavidKnott** [comment]
@pdaian I'll look into this right away

**Comment by DavidKnott** [comment]
@pdaian Closing this due to PR #377.
