### ISSUE TITLE
Exception to fix for logging events

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/viper#413]
### What's your issue about?

There are 2 (perhaps boils down to one) bugs in relation to logging events, that are throwing exceptions:

1.)
```python
MyLog: __log__({arg1: bytes <= 3})

def foo(x: bytes <= 3):
    log.MyLog(x)
```
```
Traceback (most recent call last):
  File "./viper_bin", line 25, in <module>
    print('0x' + compiler.compile(code).hex())
  File "/home/jacques/projects/viper/viper/compiler.py", line 11, in compile
    lll = optimizer.optimize(parser.parse_tree_to_lll(parser.parse(code), code))
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 336, in parse_tree_to_lll
    sub.append(parse_func(_def, _globals, {**{'self': sigs}, **contracts}, origcode))
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 426, in parse_func
    ['seq'] + clampers + [parse_body(c, context) for c in code.body] + ['stop']
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 426, in <listcomp>
    ['seq'] + clampers + [parse_body(c, context) for c in code.body] + ['stop']
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 437, in parse_body
    return parse_stmt(code, context)
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 966, in parse_stmt
    return Stmt(stmt, context).lll_node
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 56, in __init__
    self.lll_node = self.stmt_table[stmt_type]()
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 63, in expr
    return Stmt(self.stmt.value, self.context).lll_node
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 56, in __init__
    self.lll_node = self.stmt_table[stmt_type]()
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 144, in call
    inargs, inargsize, inarg_start = pack_logging_data(data_types, data, self.context)
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 1018, in pack_logging_data
    holder, maxlen = pack_args_by_32(holder, maxlen, arg, typ, context, context.new_placeholder(BaseType(32)))
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 993, in pack_args_by_32
    for c in arg.s:
AttributeError: 'Name' object has no attribute 's'
```
2.)
```python
MyLog: __log__({arg1: indexed(bytes <= 3)})

def foo(x: bytes <= 3):
    log.MyLog(x)
```
```
Traceback (most recent call last):
  File "./viper_bin", line 25, in <module>
    print('0x' + compiler.compile(code).hex())
  File "/home/jacques/projects/viper/viper/compiler.py", line 11, in compile
    lll = optimizer.optimize(parser.parse_tree_to_lll(parser.parse(code), code))
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 336, in parse_tree_to_lll
    sub.append(parse_func(_def, _globals, {**{'self': sigs}, **contracts}, origcode))
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 426, in parse_func
    ['seq'] + clampers + [parse_body(c, context) for c in code.body] + ['stop']
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 426, in <listcomp>
    ['seq'] + clampers + [parse_body(c, context) for c in code.body] + ['stop']
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 437, in parse_body
    return parse_stmt(code, context)
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 966, in parse_stmt
    return Stmt(stmt, context).lll_node
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 56, in __init__
    self.lll_node = self.stmt_table[stmt_type]()
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 63, in expr
    return Stmt(self.stmt.value, self.context).lll_node
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 56, in __init__
    self.lll_node = self.stmt_table[stmt_type]()
  File "/home/jacques/projects/viper/viper/parser/stmt.py", line 143, in call
    topics, stored_topics = pack_logging_topics(event.event_id, topics, topics_types, self.context)
  File "/home/jacques/projects/viper/viper/parser/parser.py", line 981, in pack_logging_topics
    input = base_type_conversion(input, input.typ, typ)
  File "/home/jacques/projects/viper/viper/parser/parser_utils.py", line 401, in base_type_conversion
    raise TypeMismatchException("Base type conversion from or to non-base type: %r %r" % (frm, to))
viper.exceptions.TypeMismatchException: Base type conversion from or to non-base type: bytes <= 3 bytes <= 3

```

### How can it be fixed?

Follow the tail of the exception ;)

#### Cute Animal Picture

![](http://i0.kym-cdn.com/entries/icons/original/000/008/414/cute-animals-5-animals-9403312-650-456.jpg)

**Comment by DavidKnott** [comment]
I'm on it!

**Comment by fubuloubu** [comment]
I had a similar issue with logs: #406

Perhaps the rampant use of `arg` should be revisited lol

**Comment by DavidKnott** [comment]
I believe this issue has been fixed, closing it.
