### ISSUE TITLE
TypeMismatchException doesn't show lineno if raised from `log` call

### ISSUE THREAD

**Issue by adhikasp** [ethereum/viper#498]
### What's your issue about?

`TypeMismatchException` doesn't show line number if the error was raised from `log` call.

```py
SomeLog: __log__({
    _var: num256
})

some_var: num

@public
def some_func():
    log.SomeLog(self.some_var) # Error here, should be typecasted
```

Produces the following error

```
Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/viper", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/c/Workspace/viper/bin/viper", line 31, in <module>
    print('0x' + compiler.compile(code).hex())
  File "/mnt/c/Workspace/viper/viper/compiler.py", line 11, in compile
    lll = optimizer.optimize(parser.parse_tree_to_lll(parser.parse(code), code))
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 369, in parse_tree_to_lll
    o = parse_other_functions(o, otherfuncs, _globals, sigs, external_contracts, origcode)
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 334, in parse_other_functions
    sub.append(parse_func(_def, _globals, {**{'self': sigs}, **external_contracts}, origcode))
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 452, in parse_func
    ['seq'] + clampers + [parse_body(c, context) for c in code.body] + ['stop']
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 452, in <listcomp>
    ['seq'] + clampers + [parse_body(c, context) for c in code.body] + ['stop']
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 463, in parse_body
    return parse_stmt(code, context)
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 635, in parse_stmt
    return Stmt(stmt, context).lll_node
  File "/mnt/c/Workspace/viper/viper/parser/stmt.py", line 59, in __init__
    self.lll_node = self.stmt_table[stmt_type]()
  File "/mnt/c/Workspace/viper/viper/parser/stmt.py", line 66, in expr
    return Stmt(self.stmt.value, self.context).lll_node
  File "/mnt/c/Workspace/viper/viper/parser/stmt.py", line 59, in __init__
    self.lll_node = self.stmt_table[stmt_type]()
  File "/mnt/c/Workspace/viper/viper/parser/stmt.py", line 161, in call
    inargs, inargsize, inarg_start = pack_logging_data(data_types, data, self.context)
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 705, in pack_logging_data
    holder, maxlen = pack_args_by_32(holder, maxlen, arg, typ, context, context.new_placeholder(BaseType(32)))
  File "/mnt/c/Workspace/viper/viper/parser/parser.py", line 664, in pack_args_by_32
    input = base_type_conversion(input, input.typ, typ)
  File "/mnt/c/Workspace/viper/viper/parser/parser_utils.py", line 438, in base_type_conversion
    raise TypeMismatchException("Typecasting from base type %r to %r unavailable" % (frm, to), pos)
viper.exceptions.TypeMismatchException: Typecasting from base type num to num256 unavailable
```

No information about lineno nor code snippet could be found in the stack trace.

#### Cute Animal Picture

![a cute animal picture here](https://cdn.pixabay.com/photo/2017/10/06/19/12/squirrel-2824272_960_720.jpg)

**Comment by fubuloubu** [comment]
Definitely an issue, thanks for reporting.

In general, I think compiler errors shouldn't necessarily show the Python backtrace of what went wrong, only showing the code (file, line number, like 3-4 lines of the surrounding code for context) that produced the error. @DavidKnott @jacqueswww, what do you think?
